name: Run my python

on: 
  push: # do this ever time
jobs:
  build:
    name: set up enviroment
    runs-on: ubuntu-lastest
    steps:
    - uses: actions/checkout@v2 # what kind of github action version to use    
    - name: Run my python
      run: |
        python3 test1.py
