name: Run my python

on: 
  push: # do this ever time

jobs:
  build:
  name: set up enviroment
  run-on: ubuntu-lastest
  steps:
  - uses: action/checkout@v2
  - name: Run my python
    name: |
      python3 test1.py
